global:
  email-reply-to: anosenzo@salesforce.com
  email-only-last-committer-on-dev-branch: true
  production-branches:
    - master
    - W-18021352-TEST-STRATA
  notifications:
    event: always
    on-production-branches-only: true
    slack-channels:
      - D19NN7B96 # direct message Alejandro Nosenzo

stages:
  build:
    # this user-defined step provides build/utest coverage for the repo
    - step:
        name: mvn-test
        # a list of available and approved images can be found here:
        # https://confluence.internal.salesforce.com/display/ZEN/Docker+Images
        image: docker.repo.local.sfdc.net/sfci/docker-images/sfdc_centos7_java_build
        commands:
          - mvn verify