global:
  email-reply-to: anosenzo@salesforce.com
  email-only-last-committer-on-dev-branch: true
  production-branches:
    - master
    - W-18021352-TEST-STRATA
  notifications:
    event: always
    on-production-branches-only: true
    slack-channels:
      - D19NN7B96 # direct message Alejandro Nosenzo

stages:
  precheck:
    - step:
        name: snapshot-check
        image: docker.repo.local.sfdc.net/sfci/docker-images/sfdc_rhel9:85
        when:
          - operator: EQ
            value: $$IS_PRODUCTION_BRANCH
            other: "true"
          - operator: NEQ
            value: $$BRANCH_NAME
            other: develop
        commands:
          - dnf install -y -q xmlstarlet
          - bash script/check-snapshots.sh

  build:
    - step:
        name: unit-test
        image: docker.repo.local.sfdc.net/sfci/docker-images/sfdc_rhel9_java_build/java8:202
        environment:
          - name: NEXUS_BASE_URL
          - name: NEXUS_USERNAME
          - name: NEXUS_PASSWORD
        commands:
          - mvn --no-transfer-progress --show-version --settings settings.xml clean install

  package:
    - docker-build

  integration-test:
    - sonarqube:
        enabled: false

  publish:
    - docker-push
    - step:
        name: create-git-tag
        image: docker.repo.local.sfdc.net/sfci/docker-images/sfdc_rhel9_devel:49
        when:
          - operator: EQ
            value: $$IS_PRODUCTION_BRANCH
            other: "true"
          - operator: NEQ
            value: $$BRANCH_NAME
            other: develop
        environment:
          - name: SFCI_PRODUCTION_BRANCH_BUILD_VERSION
        commands:
          - git tag -f "v${SFCI_PRODUCTION_BRANCH_BUILD_VERSION}"