global:
  email-reply-to: anosenzo@salesforce.com
  email-only-last-committer-on-dev-branch: true
  production-branches:
    - master
    - W-18021352-TEST-STRATA-2
  notifications:
    event: always
    on-production-branches-only: true
    slack-channels:
      - D19NN7B96 # direct message Alejandro Nosenzo

stages:
  build:
    - step:
        name: mvn-build
        # a list of available and approved images can be found here:
        # https://confluence.internal.salesforce.com/display/ZEN/Docker+Images
        image: docker.repo.local.sfdc.net/sfci/docker-images/sfdc_centos7_java_build:latest
        commands:
          - rm -rf /root/.m2/repository/
          - ln -s /cix/tmp/.strata/.m2/repository /root/.m2/repository
          - mvn install
  publish:
    - maven-publish:
          maven-publish-jar-image: docker.repo.local.sfdc.net/sfci/docker-images/sfdc_centos7_java_build:latest