global:
  email-reply-to: anosenzo@salesforce.com
  email-only-last-committer-on-dev-branch: true
  production-branches:
    - master
    - W-18021352-TEST-STRATA-2
    - W-18021352
  notifications:
    event: always
    on-production-branches-only: true
    slack-channels:
      - D19NN7B96 # direct message Alejandro Nosenzo
  enable-concurrent-builds: false

stages:
  build:
    - step:
        name: build-and-test
        # a list of available and approved images can be found here:
        # https://confluence.internal.salesforce.com/display/ZEN/Docker+Images
        image: docker.repo.local.sfdc.net/sfci/docker-images/sfdc_rhel9_java_build:latest
        environment:
          - name: NEXUS_BASE_URL
          - name: NEXUS_USERNAME
          - name: NEXUS_PASSWORD
          - name: MAVEN_VERSION
            value: '3.9.9'
          - name: MAVEN_TAR_DOWNLOAD_SHA512
            value: a555254d6b53d267965a3404ecb14e53c3827c09c3b94b5678835887ab404556bfaf78dcfe03ba76fa2508649dca8531c74bca4d5846513522404d48e8c4ac8b

        commands:
          - git --version
          - dnf remove -y maven
          - sh download_maven.sh
          - export PATH=$(sh download_maven.sh)/bin:${PATH}
          - export
          - echo $PATH
          - mvn --version
          # test 2
          #          - rm -rf /root/.m2/repository/
          #          - ln -s /cix/tmp/.strata/.m2/repository /root/.m2/repository
          - mvn help:evaluate -Dexpression=settings.localRepository -q -DforceStdout
          - mvn --no-transfer-progress --show-version --settings settings.xml clean install
          - mvn help:evaluate -Dexpression=settings.localRepository -q -DforceStdout
  publish:
    - maven-publish:
        maven-publish-jar-image: docker.repo.local.sfdc.net/sfci/docker-images/sfdc_rhel9_java_build:latest