global:
  email-reply-to: anosenzo@salesforce.com
  email-only-last-committer-on-dev-branch: true
  production-branches:
    - master
    - W-18021352-TEST-STRATA-2
  notifications:
    event: always
    on-production-branches-only: true
    slack-channels:
      - D19NN7B96 # direct message Alejandro Nosenzo
  enable-concurrent-builds: false

stages:
  build:
    - step:
        name: build-and-test
        # a list of available and approved images can be found here:
        # https://confluence.internal.salesforce.com/display/ZEN/Docker+Images
        image: docker.repo.local.sfdc.net/sfci/docker-images/sfdc_rhel9_java_build:latest
        environment:
          - name: NEXUS_BASE_URL
          - name: NEXUS_USERNAME
          - name: NEXUS_PASSWORD
          - name: MAVEN_VERSION
            value: '3.9.9'
          - name: MAVEN_TAR_DOWNLOAD_SHA1
            value:

        commands:
          - git --version
          - sh setup_build.sh
          # test 2
          #          - rm -rf /root/.m2/repository/
          #          - ln -s /cix/tmp/.strata/.m2/repository /root/.m2/repository
          - mvn --no-transfer-progress --show-version --settings settings.xml clean install
  publish:
    - maven-publish:
        maven-publish-jar-image: docker.repo.local.sfdc.net/sfci/docker-images/sfdc_rhel9_java_build:latest