upstreamProjects:
  Mule-runtime/metadata-model-api/support/1.5.x,
  Mule-runtime/mule-artifact-declaration/support/1.5.x
# Comment public setting to get oldMuleArtifact 4.3.0 from private repo till we move them to the public Repo
# Uncomment it after they are copied
# "mavenSettingsXmlId" : "mule-runtime-maven-settings-MuleSettings",
projectType: runtime
