upstreamProjects:
  Mule-runtime/metadata-model-api/1.4.0-20241021-WITH-W-17110125,
  Mule-runtime/mule-artifact-declaration/1.4.0-20241021-WITH-W-17110125
# Comment public setting to get oldMuleArtifact 4.3.0 from private repo till we move them to the public Repo
# Uncomment it after they are copied
# "mavenSettingsXmlId" : "mule-runtime-maven-settings-MuleSettings",
projectType: runtime
