upstreamProjects:
  Mule-runtime/metadata-model-api/1.6.7-DRY-RUN,
  Mule-runtime/mule-artifact-declaration/1.6.6-DRY-RUN
# Comment public setting to get oldMuleArtifact 4.3.0 from private repo till we move them to the public Repo
# Uncomment it after they are copied
# "mavenSettingsXmlId" : "mule-runtime-maven-settings-MuleSettings",
projectType: runtime
jdkTool: OPEN-JDK17
additionalTestConfigs:
  jdk8:
    testJdkTool: OPEN-JDK8
  jdk11:
    testJdkTool: OPEN-JDK11
